# Generated by Django 3.1.5 on 2021-01-19 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_grid_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grid',
            name='color',
        ),
        migrations.AlterField(
            model_name='grid',
            name='animation_order',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='blue', max_length=200)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spots.grid')),
            ],
        ),
    ]
